# Generated by Django 3.0.5 on 2021-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210120_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
